import re
import threading
import time
from collections import Counter

import numpy as np
from rank_bm25 import BM25Okapi

from .domain import ServiceError, is_bug, issue_text


def tokenize(text):
    # Keep exact symbols and versions; add constituent words for ordinary text matching.
    whole = re.findall(r'[\w]+(?:[.:/\\+\-][\w]+)*', text.casefold(), flags=re.UNICODE)
    result = []
    for token in whole:
        result.append(token)
        parts = re.findall(r'[^\W_]+', token, re.UNICODE)
        if len(parts) > 1:
            result.extend(parts)
    return result


def fuse(lexical, semantic, constant=60, window=50):
    scores = {}
    for ranking in (lexical[:window], semantic[:window]):
        for rank, (number, _) in enumerate(ranking, 1):
            scores[number] = scores.get(number, 0.0) + 1.0 / (constant + rank)
    return sorted(scores.items(), key=lambda x: (-x[1], x[0]))


class SearchEngine:
    def __init__(self, store, semantic):
        self.store, self.semantic = store, semantic
        self.indices = {}
        self.lock = threading.RLock()

    def index(self, snapshot):
        key = (snapshot['repository'], snapshot['version'])
        with self.lock:
            if key not in self.indices:
                issues = [x for x in snapshot['issues'] if is_bug(x, snapshot['bug_labels'])]
                if not issues:
                    raise ServiceError('no_bug_issues', 'Bug Issue가 없습니다. 저장소의 Bug 레이블을 추가로 지정하세요.', 409)
                tokens = [tokenize(issue_text(x)) or ['__empty_document__'] for x in issues]
                bm25 = BM25Okapi(tokens)
                # Positive Robertson IDF avoids negative/zero ranking on tiny corpora.
                frequencies = Counter(term for doc in bm25.doc_freqs for term in doc)
                for term, frequency in frequencies.items():
                    bm25.idf[term] = float(np.log(1 + (len(tokens) - frequency + .5) / (frequency + .5)))
                self.indices = {k: v for k, v in self.indices.items() if k[0] != snapshot['repository']}
                self.indices[key] = (issues, tokens, bm25)
            return self.indices[key]

    def ranking(self, snapshot, query, method, exclude=None):
        issues, tokens, bm25 = self.index(snapshot)
        # Section headings are generated by our API, not user search terms.
        lexical_query = re.sub(r'(?m)^\[(?:PROBLEM|ERROR|ENVIRONMENT)\]\n', '', query)
        query_tokens = tokenize(lexical_query)
        query_set = set(query_tokens)
        lexical = []
        if method in {'bm25', 'hybrid'}:
            scores = bm25.get_scores(query_tokens)
            lexical = sorted([(x['number'], float(scores[i])) for i, x in enumerate(issues)
                              if x['number'] != exclude and query_set.intersection(tokens[i])],
                             key=lambda x: (-x[1], x[0]))
        semantic = []
        if method in {'semantic', 'hybrid'}:
            scores = self.semantic.scores(snapshot, query)
            semantic = sorted([(n, s) for n, s in scores.items() if n != exclude], key=lambda x: (-x[1], x[0]))
        return fuse(lexical, semantic) if method == 'hybrid' else lexical if method == 'bm25' else semantic

    def search(self, repository, query, method='hybrid', top_k=5):
        start = time.perf_counter()
        snapshot = self.store.get(repository)
        if not snapshot:
            raise ServiceError('repository_not_ready', '먼저 저장소를 분석하세요.', 409)
        ranked = self.ranking(snapshot, query, method)
        records = {x['number']: x for x in snapshot['issues']}
        results = []
        for number, score in ranked[:top_k]:
            issue = records[number]
            results.append({'number': number, 'title': issue['title'], 'state': issue['state'],
                            'labels': [x['name'] if isinstance(x, dict) else x for x in issue.get('labels', [])],
                            'url': f'https://github.com/{repository}/issues/{number}',
                            'excerpt': (issue.get('body') or '')[:420], 'score': score})
        return {'repository': repository, 'method': method,
                'score_type': {'bm25': 'bm25', 'semantic': 'cosine_similarity', 'hybrid': 'rrf'}[method],
                'snapshot_version': snapshot['version'], 'collected_at': snapshot['collected_at'],
                'partial': snapshot['partial'], 'elapsed_ms': round((time.perf_counter() - start) * 1000, 1),
                'results': results}
